@host=http://localhost:5078

GET {{host}}/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNWVkMjA3ZS01YmRhLTRiNjktYjRhNC1kZjIzY2Y0YjRmMTUiLCJnaXZlbl9uYW1lIjoiRmlzdCIsImZhbWlseV9uYW1lIjoiTGFzdCIsImp0aSI6IjA2OWM2ZDFhLTM1YmYtNGQxYS05MjE5LTI0MTdiMGRlNTdlYSIsImV4cCI6MTY4NjE4NDAyNSwiaXNzIjoiQ0FEREQiLCJhdWQiOiJDQURERCJ9.YzQ-wPC0CVsv_EQ_GF18_UcOW5sj2jC-uRUw3kk4Sj8